add_newline = false
format = "$directory$fill$python$nodejs$git_branch$git_status$cmd_duration$line_break$character"
fill.symbol = " "

[character]
success_symbol = "[îŠ…](#6e95bd)"
error_symbol = "[îŠ…](#da4b52)"
vicmd_symbol = "[îŸ…](#dc8c61)"

[directory]
format = "[î‚¶]($style)[î—¿  ](bg:#171717 fg:#6e95bd)[$path](bg:#171717 fg:#b7b7b7 bold)[î‚´ ]($style)"
style = "bg:none fg:#171717"
truncation_length = 3
truncate_to_repo = false

[git_branch]
format = "[î‚¶]($style)[[ï‡“  ](bg:#171717 fg:#6fadea bold)$branch](bg:#171717 fg:#b7b7b7)[î‚´ ]($style)"
style = "bg:none fg:#171717"

[git_status]
format = "[î‚¶]($style)[$all_status$ahead_behind](bg:#171717 fg:#b7b7b7 bold)[î‚´ ]($style)"
style = "bg:none fg:#171717"
conflicted = "="
ahead = "â‡¡${count}"
behind = "â‡£${count} "
diverged = "â†‘${ahead_count} â‡£${behind_count} "
up_to_date = "ï€Œ "
untracked = "?${count} "
stashed = "ï£• "
modified = "!${count} "
staged = "+${count} "
renamed = "Â»${count} "
deleted = "ï‡¸ ${count} "

[cmd_duration]
min_time = 1
format = "[î‚¶]($style)[[ï”   ](bg:#171717 fg:#6e95bd bold)$duration](bg:#171717 fg:#b7b7b7 bold)[î‚´]($style)"
disabled = false
style = "bg:none fg:#171717"

[python]
format = "[î‚¶]($style)[[ğŸ ](bg:#171717 fg:#6e95bd)$virtualenv](bg:#171717 fg:#b7b7b7 bold)[î‚´ ]($style)"
style = "bg:none fg:#171717"

[nodejs]
format = "[î‚¶]($style)[[ó°™  ](bg:#171717 fg:#6e95bd)$version](bg:#171717 fg:#b7b7b7 bold)[î‚´ ]($style)"
style = "bg:none fg:#171717"
